### PR TITLE
Remove deployment to cloud.gov

### PR DESCRIPTION
**Pull request by jbrown-xentity**
Missed that this was already setup to auto-deploy to cloud.gov in #16. Removes the deployment code.

### CODE REVIEW

**Review by nickumia-reisys — APPROVED** [review]
Do we also want to delete the keys associate from this in the github secrets?

**Comment by jbrown-xentity** [comment]
> Do we also want to delete the keys associate from this in the github secrets?

@mogul @adborden you are the only 2 that can handle this... Want to remove the secrets from GitHub actions?

**Comment by mogul** [comment]
I took care of removing the CF deployer secrets. These couple are still there... I've left them in case we need to recover them (from within a GitHub Action tmate session, for example) at a later time.
image

**Comment by jbrown-xentity** [comment]
I removed the service-keys on cloud.gov across all spaces for this app...

**Pull request merged**
